### ISSUE TITLE
Body empty?

### ISSUE THREAD

**Issue by kobleistvan** [amida-tech/withings-lib#11] opened 2015-09-20 16:09 UTC
Hey there, I get Status 0, Body: {} for daily steps and daily calories. Didn't get to check the rest yet. Help?

**Comment by jsachs** [comment] 2015-09-20 17:34
@kobleistvan, if you're getting `status: 0`, it means the operation was successful. If the body is still coming back empty, my guess is that there isn't actually data for the date you requested.

One thought is that it has to do with timezone. May I ask which timezone you are making the request from, as well as the timezone in which you are using Withings? We haven't added any timezone support to the API yet, so this could be the issue.

**Comment by kobleistvan** [comment] 2015-09-20 17:41
The account was made in UTC+2 in Bucharest time zone, and now I'm in London time zone. But I don't think it should matter. I don't care about the time really, just the date. I even worked a bit in your library and forced an explicit date of yesterday. And yes, I do have data on the specific days.. Still, no luck :/ Does it work for you atm?

**Comment by jsachs** [comment] 2015-09-20 17:49
It appears to be working for me. We have a demo app on Heroku--I'm going to make a few quick updates then send you the link so you can try it out with your own account.

**Comment by kobleistvan** [comment] 2015-09-20 17:56
Ok. Please do! Thank you very much!
Btw, I didn't find any timezone settings in the Withings Settings page..

**Comment by kobleistvan** [comment] 2015-09-20 17:58
Btw, in the example on the NPM and GitHub page, you're redirecting to '/activity' in the callback function, but you only have 'activity/steps' :) It's confusing for newbies.

**Comment by jsachs** [comment] 2015-09-20 18:56
I have to drive for a few hours, should be back online with these updates by this evening.

**Comment by kobleistvan** [comment] 2015-09-20 18:57
Alright :) Thank you very much!

**Comment by jsachs** [comment] 2015-09-21 03:29
@kobleistvan quick update, the demo app is good to go (after fighting with some hidden changes by Heroku). It looks like Withings may have done some stealth changes with their API so I'm going to look into that tonight.

[Demo dashboard here](https://withings-lib.herokuapp.com/dashboard). To use, click authorize to log into your Withings account. The dashboard will then show all steps and weight data, as well as steps and cals data for the current day.

**Comment by jsachs** [comment] 2015-09-21 05:28
So, go check out the demo app and let me know what you find. If you look at lines 152 and 166 of `/lib/withings.js`, you'll see that these particular methods get the steps and calories data directly from the response body, so if there is no data for the day, you'll just get `""`.

The point on the `/activity` redirect is a good callout and I'm going to change it now.

**Comment by kobleistvan** [comment] 2015-09-21 06:02
@jsachs Thanks for the update, I will check out the code today. Regarding the empty body, I saw that you fetch the key 'body->steps', but the body is empty, so having no key 'steps' in it returns an undefined value. Same goes with calories.

**Comment by kobleistvan** [comment] 2015-09-26 21:57
Hey @jsachs , I looked into the demo app, It gives me Steps and Weight, but the panes are empty at daily steps and daily calories. =/

**Comment by kobleistvan** [comment] 2015-09-26 22:02
I currently don't have any withings devices (tracker) and none connected to the account. But I use the healthmate app on android and it DOES record the steps, and uploads it to my withings account. Could that be an issue?

**Comment by kobleistvan** [comment] 2015-09-26 22:10
Even though I do get stepcount in Steps pane:

{"status":0,"body":{"activities":[{"date":"2015-06-01","steps":2895,"distance":2288.313,"calories":303.28,"totalcalories":2435.54,"elevation":0,"soft":4860,"moderate":420,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-02","steps":6,"distance":4.725,"calories":4.14,"totalcalories":2272.13,"elevation":0,"soft":120,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-03","steps":6104,"distance":4870.687,"calories":412.61,"totalcalories":2578.01,"elevation":0,"soft":420,"moderate":3600,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-04","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-05","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-06","steps":50,"distance":39.379,"calories":21.64,"totalcalories":2277,"elevation":0,"soft":600,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-07","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-08","steps":1494,"distance":1213.239,"calories":165.33,"totalcalories":2359.14,"elevation":0,"soft":2520,"moderate":420,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-09","steps":1666,"distance":1312.107,"calories":184.62,"totalcalories":2367.38,"elevation":0,"soft":3120,"moderate":240,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-10","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-11","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-12","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-13","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-14","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-15","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-16","steps":1178,"distance":944.324,"calories":184.56,"totalcalories":2349.96,"elevation":0,"soft":3900,"moderate":120,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-17","steps":3,"distance":2.363,"calories":2.07,"totalcalories":2271.64,"elevation":0,"soft":60,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-18","steps":904,"distance":738.739,"calories":112.6,"totalcalories":2326.93,"elevation":0,"soft":1920,"moderate":240,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-19","steps":2722,"distance":2189.348,"calories":349.8,"totalcalories":2439.44,"elevation":0,"soft":6360,"moderate":540,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-20","steps":0,"distance":0,"calories":0,"totalcalories":2271.15,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-21","steps":0,"distance":0,"calories":0,"totalcalories":2271.15,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-22","steps":0,"distance":0,"calories":0,"totalcalories":2271.15,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-23","steps":3714,"distance":2928.053,"calories":350.11,"totalcalories":2474.48,"elevation":0,"soft":5400,"moderate":180,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-24","steps":3223,"distance":2580.899,"calories":308.65,"totalcalories":2450.38,"elevation":0,"soft":3720,"moderate":1200,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-25","steps":0,"distance":0,"calories":0,"totalcalories":2271.15,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-26","steps":0,"distance":0,"calories":0,"totalcalories":2271.15,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-27","steps":1150,"distance":905.716,"calories":209.42,"totalcalories":2352.73,"elevation":0,"soft":4860,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-28","steps":1808,"distance":1423.943,"calories":280.18,"totalcalories":2390.34,"elevation":0,"soft":6000,"moderate":120,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-29","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"},{"date":"2015-06-30","steps":0,"distance":0,"calories":0,"totalcalories":2064.44,"elevation":0,"soft":0,"moderate":0,"intense":0,"timezone":"Europe/Bucharest"}]}}

**Comment by jsachs** [comment] 2015-09-27 02:27
So looking at the dates that came back... it's because the demo app is still hard-coded for the month of June. Something I still need to fix...

When I was testing it myself, I was able to get data from the current date. At this point I would recommend walking through the API workflow [here](http://oauth.withings.com/api). You'll be able to see everything behind the scenes, as well as make a direct API call for daily measures. If this works for you, it means I've screwed something up in the way daily data is fetched. If it still doesn't work for you, it may point to the way that Healthmate is recording the data.

**Comment by kobleistvan** [comment] 2015-09-28 11:19
@jsachs : So I just wanted to let you know that  today I just tested it with a girl, she has an activity tracker 24/7, got back steps, but no 'daily steps'. The data were synchronized with withings. :/ No idea what the issue might be. Couldn't get the data from the API workflow yet, had some issues encoding the hmac into base64 and always got issues with the validity of the oauth token. I'll try again today

**Comment by jsachs** [comment] 2015-09-28 13:16
@kobleistvan thanks for the info. I'll take a closer look at the daily metrics this evening. It sounds like I've overlooked something in the API.

**Comment by kobleistvan** [comment] 2015-09-28 13:41
alright. Thanks :)

**Comment by kobleistvan** [comment] 2015-09-28 15:51
Can I fork your herokuApp? I'm in a conversation with withings tech support and trying to see what the issue is, and can work easier with the testApp that you put on heroku.

**Comment by jsachs** [comment] 2015-09-28 16:01
Of course! Should be amida-tech/withings-demo

**Comment by kobleistvan** [comment] 2015-09-28 16:02
Thankyou! I'll keep you updated :)

**Comment by kobleistvan** [comment] 2015-09-28 16:39
OK, so I didn't change anything to my code, I've no idea if the Withings tech support team fiddled with anything, but now it works. I can get the current step count :)

**Comment by kobleistvan** [comment] 2015-09-28 16:44
Your demo app still gives me an empty body response for some reason, but mine gives a valid stepcount. No idea why.
![1](https://cloud.githubusercontent.com/assets/6638917/10142111/867a3998-6608-11e5-997a-63145074a3f4.PNG)
![2](https://cloud.githubusercontent.com/assets/6638917/10142110/8678a10a-6608-11e5-8dd1-676f7641ad49.PNG)
![3](https://cloud.githubusercontent.com/assets/6638917/10142112/867ce17a-6608-11e5-808b-e4ffe6983f83.PNG)

**Comment by jsachs** [comment] 2015-09-28 17:46
One more idea on the timezone front: could you post the API calls you are making using `withings-lib`, including the parameters being passed?

**Comment by kobleistvan** [comment] 2015-09-28 17:49
``` javascript
var express = require('express');
var router = express.Router();
var config=require('../config.json')[process.env.NODE_ENV || 'dev'];
var Withings = require('withings-lib');

var options = {
  consumerKey: 'DELETEDFROMTHISPOST',
  consumerSecret: 'DELETEDFROMTHISPOST',
  callbackUrl: 'http://192.168.1.111:5000/withings/callback',
  requestToken: '',
  requestTokenSecret: '',
  accessToken: '',
  accessTokenSecret: '',
  userID: '',
  verifier: ''
};

// OAuth flow
router.get('/', function (req, res) {
  // Create an API client and start authentication via OAuth
  var client = new Withings(options);

  client.getRequestToken(function (err, token, tokenSecret) {
    if (err) {
      // Throw error
      return console.error(err);
    }
    options.requestToken = token;
    options.requestTokenSecret = tokenSecret;

    res.redirect(client.authorizeUrl(token, tokenSecret));
  });
});

// On return from the authorization
router.get('/callback', function (req, res) {
  options.verifier = req.query.oauth_verifier;
  options.userID = req.query.userid;

  var client = new Withings(options);

  // Request an access token
  client.getAccessToken(options.requestToken, options.requestTokenSecret, options.verifier,
    function (err, token, secret) {
      if (err) {
        return console.error(err);
      }

      options.accessToken = token;
      options.accessTokenSecret = secret;

      // res.redirect('/withings/activity/steps');
      res.redirect('/withings/activity/calories');
    }
  );
});

// Display today's steps for a user
router.get('/activity/steps', function (req, res) {
  var client = new Withings(options);

  var a = client.getDailySteps(new Date(), function(err, data) {
    if (err) {
      console.error("err:", err);
        res.send(err);
    }
    console.log("data:", data);
    res.json(data);
  })
});

// Display today's steps for a user
router.get('/activity/calories', function (req, res) {
  var client = new Withings(options);

  var a = client.getDailyCalories(new Date(2015-09-19), function(err, data) {
    if (err) {
      console.error("err:", err);
        res.send(err);
    }
    console.log("data:", data);
    res.json(data);
  })
});

// Display today's steps for a user
router.get('/activity/weight', function (req, res) {
  var client = new Withings(options);

  var a = client.getWeightMeasures(new Date(2015-07-20) ,new Date(), function(err, data) {
    if (err) {
      console.error("err:", err);
        res.send(err);
    }
    console.log("data:", data);
    res.json(data);
  })
});

// Display today's steps for a user
router.get('/activity/pulse', function (req, res) {
  var client = new Withings(options);

  var a = client.getPulseMeasures(new Date(2015-07-20) ,new Date(), function(err, data) {
    if (err) {
      console.error("err:", err);
        res.send(err);
    }
    console.log("data:", data);
    res.json(data);
  })
});

module.exports = router;
```

**Comment by kobleistvan** [comment] 2015-09-28 17:52
Ignore the bad comments of the functions.. copy pasted :)

**Comment by jsachs** [comment] 2015-09-28 17:59
The code looks pretty much identical. I wish I could chalk it up to timezone but it's still the 28th in Bucharest.

I'm at a loss and it's very frustrating.

I guess since the issue is with the library and not the demo app, and it looks like the library is working for you now, we can close this issue. I'll keep an eye on the demo app though.

**Comment by kobleistvan** [comment] 2015-09-28 18:01
Although I have data from bucharest, I'm for 2 weeks in London. But yah. So far so good. :) Thankyou for everything!

**Closed as completed** 2015-09-28 18:39 UTC
